Phraseanet/lib/Alchemy/Phrasea/Controller/Api/Result.php
<?php

/*
 * This file is part of Phraseanet
 *
 * (c) 2005-2014 Alchemy
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Alchemy\Phrasea\Controller\Api;

use Alchemy\Phrasea\ControllerProvider\Api\V1;
use Alchemy\Phrasea\ControllerProvider\Api\V3;
use Alchemy\Phrasea\Utilities\Stopwatch;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Yaml\Dumper;

class Result
{
    private static $defaultVersion = '1.0.0';

    /** @var string */
    private $responseTime;

    /** @var integer */
    private $code = 200;

    /** @var string */
    private $errorType;

    /** @var string */
    private $errorMessage;

    /** @var string */
    private $errorDetails;

    /** @var Request */
    private $request;

    /** @var mixed */
    private $data;

    /** @var string */
    private $responseType;

    /** @var string */
    private $version;

    const FORMAT_JSON = 'json';
    const FORMAT_YAML = 'yaml';
    const FORMAT_JSONP = 'jsonp';

    const FORMAT_JSON_EXTENDED = 'json+extended';
    const FORMAT_YAML_EXTENDED = 'yaml+extended';
    const FORMAT_JSONP_EXTENDED = 'jsonp+extended';

    const ERROR_BAD_REQUEST = 'Bad Request';
    const ERROR_UNAUTHORIZED = 'Unauthorized';
    const ERROR_FORBIDDEN = 'Forbidden';
    const ERROR_NOTFOUND = 'Not Found';
    const ERROR_MAINTENANCE = 'Service Temporarily Unavailable';
    const ERROR_METHODNOTALLOWED = 'Method Not Allowed';
    const ERROR_INTERNALSERVERERROR = 'Internal Server Error';
    const ERROR_UNACCEPTABLE = 'Unacceptable';
    const ERROR_UNPROCESSABLEENTITY = 'Unprocessable Entity';

    public function __construct(Request $request, array $data = null, $code = 200, $errorType = null, $errorMessage = null, $errorDetails = null)
    {
        $date = new \DateTime();

        $this->request = $request;
        $this->responseTime = $date->format(DATE_ATOM);
        $this->data = new \stdClass();

        $this->parseResponseType();

        $this->setData($data);
        $this->code = $code;
        $this->errorType = $errorType;
        $this->errorMessage = $errorMessage;
        $this->errorDetails = $errorDetails;
    }

    /**
     * Creates a Symfony Response
     *
     * include lapses from stopwatch(es) as server-timing headers
     *
     * @param Stopwatch[] $stopwatches
     * @return Response
     */
    public function createResponse($stopwatches=[])
    {
        $response = $this->format();
        $response->headers->set('content-type', $this->getContentType());
        // add specific timing debug
        foreach($stopwatches as $stopwatch) {
            $response->headers->set('Server-Timing', $stopwatch->getLapsesAsServerTimingHeader(), false);
        }
        $response->setStatusCode($this->getStatusCode());
        $response->setCharset('UTF-8');

        // add general timing debug
        $duration = (microtime(true) - $this->request->server->get('REQUEST_TIME_FLOAT')) * 1000.0;
        $h = '_global;' . 'dur=' . $duration;
        $response->headers->set('Server-Timing', $h, false);    // false : add header (don't replace)

        return $response;
    }


    /**
     * @param Request $request
     * @param $data
     *
     * @return Result
     */
    public static function create(Request $request, $data)
    {
        return new static($request, $data);
    }

    /**
     * @param Request $request
     * @param $code
     * @param $message
     *
     * @return Result
     *
     * @throws \InvalidArgumentException
     */
    public static function createError(Request $request, $code, $message)
    {
        $errorDetails = $message;

        switch ($code) {
            case 400:
                $errorType = self::ERROR_BAD_REQUEST;
                $errorMessage = 'Parameter is invalid or missing';
                break;
            case 401:
                $errorType = self::ERROR_UNAUTHORIZED;
                $errorMessage = 'The OAuth token was provided but was invalid.';
                break;
            case 403:
                $errorType = self::ERROR_FORBIDDEN;
                $errorMessage = 'Access to the requested resource is forbidden';
                break;
            case 404:
                $errorType = self::ERROR_NOTFOUND;
                $errorMessage = 'Requested resource is not found';
                break;
            case 405:
                $errorType = self::ERROR_METHODNOTALLOWED;
                $errorMessage = 'Attempting to use POST with a GET-only endpoint, or vice-versa';
                break;
            case 406:
                $errorType = self::ERROR_UNACCEPTABLE;
                $errorMessage = 'Request content type is not acceptable';
                break;
            case 422:
                $errorType = self::ERROR_UNPROCESSABLEENTITY;
                $errorMessage = 'Request content is unprocessable';
                break;
            case 500:
                $errorType = self::ERROR_INTERNALSERVERERROR;
                $errorMessage = 'Internal Server Error';
                break;
            case 503:
                $errorType = self::ERROR_MAINTENANCE;
                $errorMessage = 'Server is offline for maintenance, try again soon.';
                break;
            default:
                throw new \InvalidArgumentException('Unable to generate a response.');
        }

        return new static($request, null, $code, $errorType, $errorMessage, $errorDetails);
    }

    public static function createBadRequest(Request $request, $message = '')
    {
        $response = self::createError($request, 400, $message)->createResponse();
        $response->headers->set('X-Status-Code', $response->getStatusCode());

        return $response;
    }

    private function parseResponseType()
    {
        if (trim($this->request->get('callback')) !== '') {
            return $this->responseType = self::FORMAT_JSONP;
        }

        $responseTypes = array_map('strtolower', $this->request->getAcceptableContentTypes());

        if (in_array('application/json', $responseTypes)) {
            return $this->responseType = self::FORMAT_JSON;
        }
        if (in_array('application/yaml', $responseTypes)) {
            return $this->responseType = self::FORMAT_YAML;
        }
        if (in_array('text/yaml', $responseTypes)) {
            return $this->responseType = self::FORMAT_YAML;
        }

        return $this->responseType = self::FORMAT_JSON;
    }

    /**
     * Sets data to the response.
     *
     * If no datas provided, a stdClass if set,
     * so the serialized datas will be objects
     *
     * @param array $datas
     *
     * @return Result
     */
    private function setData(array $data = null)
    {
        if (null === $data || count($data) === 0) {
            $data = new \stdClass();
        }

        $this->data = $data;

        return $this;
    }

    /**
     * Formats the data and return serialized string
     *
     * @return Response
     */
    private function format()
    {
        $request_uri = sprintf('%s %s', $this->request->getMethod(), $this->request->getBasePath().$this->request->getPathInfo());

        $ret = [
            'meta' => [
                'api_version'   => $this->getVersion(),
                'request'       => $request_uri,
                'response_time' => $this->responseTime,
                'http_code'     => $this->code,
                'error_type'    => $this->errorType,
                'error_message' => $this->errorMessage,
                'error_details' => $this->errorDetails,
                'charset'       => 'UTF-8',
            ],
            'response'          => $this->data,
        ];

        switch ($this->responseType) {
            case self::FORMAT_JSON:
            default:
                return new JsonResponse($ret);
            case self::FORMAT_YAML:
                if ($ret['response'] instanceof \stdClass) {
                    $ret['response'] = [];
                }

                $dumper = new Dumper();

                return new Response($dumper->dump($ret, 8));
            case self::FORMAT_JSONP:
                $response = new JsonResponse($ret);
                $response->setCallback(trim($this->request->get('callback')));

                return $response;
                break;
        }
    }

    /**
     * @param string|null $version
     */
    public function setVersion($version)
    {
        $this->version = (string)$version;
    }

    public static function setDefaultVersion($version)
    {
        self::$defaultVersion = $version;
    }

    public function getVersion()
    {
        if (null === $this->version) {
            if ($this->request->attributes->get('api_version')) {
                $this->version = $this->request->attributes->get('api_version');
            } elseif (mb_strpos($this->request->getPathInfo(), '/api/v1') !== FALSE) {
                $this->version = V1::VERSION;
            }  elseif (mb_strpos($this->request->getPathInfo(), '/api/v3') !== FALSE) {
                $this->version = V3::VERSION;
            } else {
                $this->version = self::$defaultVersion;
            }
        }

        return $this->version;
    }

    /**
     * Returns serialized data content type
     *
     * @return string
     */
    private function getContentType()
    {
        switch ($this->responseType) {
            case self::FORMAT_JSON:
            default:
                return 'application/json';
            case self::FORMAT_YAML:
                return 'application/yaml';
            case self::FORMAT_JSONP:
                return 'text/javascript';
        }
    }

    /**
     * Returns the correct http code depending on the errors
     *
     * @return integer
     */
    private function getStatusCode()

Phraseanet/templates/web/developers/application.html.twig
{% extends "account/base.html.twig" %}

{% block title %}
    {{ "Client application" | trans }}
{% endblock %}

{% set selected = "" %}

{% block javascript %}
    {{ parent() }}
    <script type="text/javascript">
        accountApp.bootstrap({
            state: 'editApplication',
            geonameServerUrl: '{{ app['geonames.server-uri'] }}'
        });
    </script>
{% endblock %}

{% block content_account %}
    <div class="row-fluid">
        <div class="span12">
            <h1>{{ "Application" | trans }} - <strong><a class="link" href="{{ path("developers_application", {"application" : application.getId()}) }}">{{ application.getName() }}</a></strong></h1>
            <input type="hidden" value="{{ application.getId() }}" name="app_id"/>

            <div>
              <div>{{ application.getDescription() }}</div>
            </div>

            <br />

            <h1>{{ "settings OAuth" | trans }}</h1>

            <table id="app-oauth-setting" class="table table-condensed  table-bordered">
                <tbody>
                    <tr>
                        <td>Client ID</td>
                        <td>{{ application.getClientId() }}</td>
                    </tr>
                    <tr>
                        <td>Client Secret</td>
                        <td>{{ application.getClientSecret() }}</td>
                    </tr>
                    <tr>
                        <td>{{ "URL de callback" | trans }}</td>
                            {% if application.getType() == constant("DESKTOP_TYPE", application) %}
                            <td>
                                <span>{{ application.getRedirectUri() }}</span>
                            </td>
                        {% else %}
                            <td class="url_callback">
                                <span class="url_callback_input">{{ application.getRedirectUri() }}</span>
                                <a href="{{ path("submit_application_callback", {"application" : application.getId()}) }}" class="save_callback btn btn-small btn-info" style="display:none;">
                                    {{ "Save" | trans }}
                                </a>
                                <button type="button" class="modifier_callback btn btn-small">
                                      {{ "Modify" | trans }}
                                </button>
                            </td>
                        {%endif%}
                    </tr>
                    <tr>
                        <td>Authorize endpoint</td>
                        <td>{{ app["conf"].get("servername") }}api/oauthv2/authorize</td>
                    </tr>
                    <tr>
                        <td>Access endpoint</td>
                        <td>{{ app["conf"].get("servername") }}api/oauthv2/token</td>
                    </tr>
                    <tr>
                        <td>{{ "Activer le grant_type de type password pour votre application" | trans }}</td>
                        <td>
                            <input class="grant-type"
                                type="checkbox"
                                {{ application.isPasswordGranted() ? "checked='checked'" : "" }}
                                name="grant"
                                value="{{ path("submit_developers_application_authorize_grant_password", {"application" : application.getId()}) }}"
                            >
                        </td>
                    </tr>
                    {% if application.getType() == constant("WEB_TYPE", application) %}
                        <tr>
                            <td>
                                {{ "Define a webhook URL" | trans }}
                                <p style="font-size: 10px;max-width: 450px">
                                    {{ "Gives the option to your application to communicate with Phraseanet. This webhook can be used to trigger some actions on your application side." | trans }}
                                </p>
                            </td>
                            <td class="url_callback">
                                <span class="url_webhook_input">{{ application.getWebhookUrl() }}</span>
                                <a href="{{ path("submit_application_webhook", {"application" : application.getId()}) }}" class="save_webhook btn btn-small btn-info" style="display:none;">
                                    {{ "Save" | trans }}
                                </a>
                                <button type="button" class="webhook-modify-btn btn btn-small">
                                    {{ "Modify" | trans }}
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                {{ "developers:: Webhook active" | trans }}
                            </td>
                            <td>
                                <input class="update-webhook-status" type="checkbox" id="webhook_active"
                                       data-path="{{ path('developers_application_active_webhook', {"application" : application.getId()}) }}"
                                        {% if application.isWebhookActive() %} checked {% endif %}
                                       name="webhook_active"  value="1"/>
                            </td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>

            <h1>{{ "Votre token d\'access" | trans }}</h1>
            <p> {{ "Les paramétres oauth de votre application." | trans }}</p>

            <table id="app-access-token-setting table" class="table table-condensed  table-bordered">
                <tbody>
                    <tr>
                        <td>
                            {{ "Token" | trans }}
                        </td>
                        <td>
                            <span id="my_access_token">
                                {% if not token is none %}
                                  {{ token.getOauthToken()|default("") }}
                                {% else %}
                                  {{ "Le token n\'a pas encore ete genere" | trans }}
                                {% endif %}
                            </span>
                            <a id="generate_access" href="{{ path("submit_developers_application_token",{ "application" : application.getId()}) }}" class="btn btn-small btn-info">{{ "boutton::generer" | trans }}</a>
                        </td>
                    </tr>
                </tbody>
            </table>

            <h1>{{ "developers:: Events trigger this webhook" | trans }}</h1>
            <p>{{ "developers:: Select events to trigger this webhook url" | trans }}</p>
            <table class="table table-condensed  table-bordered">
                <thead>
                    <tr>
                        <th>
                            {{ "developers:: Events type" | trans }}
                        </th>
                        <th>
                            {{ "developers:: Events name" | trans }}
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for webhook_type, webhooks in webhook_event_list %}
                        <tr>
                            <td>
                                {{ webhook_type }}
                            </td>
                            <td>
                                <ul class="unstyled">
                                    {% for webhook_name, webhook_description in webhooks %}
                                        <li>
                                            <label class="checkbox" for="{{ webhook_name }}" >
                                                <input class="update-listened-event" type="checkbox" id="{{ webhook_name }}"
                                                       data-path="{{ path('developers_application_listened_event', {"application" : application.getId(), "event_name": webhook_name}) }}"
                                                        {% if webhook_name in application.getListenedEvents() %} checked {% endif %}
                                                       name="{{ webhook_name }}"  value="1"/>
                                                <strong> {{ webhook_name }} </strong>
                                                <p> {{ webhook_description }} </p>
                                            </label>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if deliveries | length > 0 %}
            <h1>{{ "Derniers envois" | trans }}</h1>
            <p> {{ "Résultats des derniers envois effectués pour cette application" | trans }}</p>

            <table id="app-access-delivery-log" class="table table-condensed table-bordered">
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th>ID</th>
                        <th>Type</th>
                        <th>Date</th>
                        <th>Status code</th>
                    </tr>
                </thead>
                <tbody>
                {% for delivery in deliveries %}
                    <tr>
                        <td>{{ delivery.isDelivered ? 'OK' : 'KO' }}</td>
                        <td style="font-family: monospace">{{ delivery.payload ? delivery.payload.id : '-' }}</td>
                        <td>{{ delivery.webhookEvent.type }}</td>
                        <td>{{ delivery.created | date }}</td>
                        <td>{{ delivery.payload ? delivery.payload.statusCode : '-' }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% endif %}

            <div class="form-actions">
                <a class="btn btn-primary" href="{{ path("developers_applications") }}">{{ "boutton::retour" | trans }}</a>
            </div>

        </div>
    </div>
{% endblock %}

Phraseanet/templates/web/developers/application_form.html.twig
{% extends "account/base.html.twig" %}

{% block title %}
    {{ "new client application" | trans }}
{% endblock %}

{% set selected = "" %}

{# form input macro #}
{% macro input(name, value, violations, property, class="", type, size) %}
    {% if violations is none %}
        <input type="{{ type|default("text") }}" name="{{ name }}" value="{{ value|e }}" size="{{ size|default(20) }}" {% if class is not empty %}class="{{ class }}"{% endif %}/>
    {% else %}
        {% set hasError = "false" %}
        {% for violation in violations %}
            {% if violation.getPropertyPath == property and hasError == "false" %}
                {% set hasError = "true" %}
                <input type="{{ type|default("text") }}" name="{{ name }}" value="{{ value  }}" size="{{ size|default(20) }}"   {% if class is not empty %}class="{{ class }}"{% endif %}/>
                <span class="help-block" style="color:red"> {{ violation.getInvalidValue  }} - {{violation.getMessage}} </span>
            {% endif %}
        {% endfor %}
        {% if hasError == "false" %}
            <input type="{{ type|default("text") }}" name="{{ name }}" value="{{ value|e }}" size="{{ size|default(20) }}"  {% if class is not empty %}class="{{ class }}"{% endif %}/>
        {% endif %}
    {% endif %}
{% endmacro %}

{# form textare macro #}
{% macro textarea(name, value, violations,property, rows, cols, class="") %}
    {% if violations is none %}
        <textarea name="{{ name }}" rows="{{ rows|default(4)}}" cols="{{cols|default(20)}}"  {% if class is not empty %}class="{{ class }}"{% endif %}>{{ value|e}}</textarea>
    {% else %}
        {% set hasError = "false" %}
        {% for violation in violations %}
            {% if violation.getPropertyPath == property and hasError == "false" %}
                {% set hasError = "true" %}
                <textarea name="{{ name }}" rows="{{ rows|default(4)}}" cols="{{cols|default(20)}}"  {% if class is not empty %}class="{{ class }}"{% endif %}>{{ violation.getInvalidValue}}</textarea>
                <span class="help-block" style="color:red"> {{violation.getMessage}} </span>
            {% endif %}
        {% endfor %}
        {% if hasError == "false" %}
                <textarea name="{{ name }}" rows="{{ rows|default(4)}}" cols="{{cols|default(20)}}"  {% if class is not empty %}class="{{ class }}"{% endif %}>{{ value|default("")|e}}</textarea>
        {% endif %}
    {% endif %}
{% endmacro %}

{% block content_account %}
<form id="form_create" action="{{ path("submit_developers_application") }}" method="POST" class="form-horizontal" style="padding: 20px; background: #757575;">
    {% if form is none %}
      {% set name, description, website, callback = "", "", "", "" %}
      {% set app_type = "web" %}
    {% else %}
      {% set name = form.name %}
      {% set description = form.description %}
      {% set website = form.website %}
      {% set callback = form.callback %}
      {% set app_type = form.type %}
    {% endif %}

    <div class="control-group">
        <label class="control-label" for="name"><b>{{ "Nom" | trans }}</b></label>
        <div class="controls">
            {{ _self.input("name", name, violations, "name", "input-xlarge") }}
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="name"><b>{{ "Description" | trans }}</b></label>
        <div class="controls">
            {{ _self.textarea("description", description, violations, "description", 5, 30, "input-xlarge") }}
        </div>
    </div>

    <div class="control-group">
        <label for="website" class="control-label"><b>{{ "Site web" | trans }}</b></label>
        <div class="controls">
            <select name="scheme-website"  class="input-mini" style="min-height: 40px;">
                <option value="http://">http://</option>
                <option value="https://">https://</option>
            </select>
            {{ _self.input("website", website, violations, "urlwebsite") }}
        </div>
    </div>

    <div class="control-group">
        <label class="control-label"><b>{{ "Type d\'application" | trans }}</b></label>
        <div class="controls">
            <label class="radio">
                <input type="radio" name="type" value="web" {{ app_type == "web" ? "checked='checked'" : "" }}/>
                {{ "Application web" | trans }}
            </label>

            <label class="radio">
                <input type="radio" name="type" value="desktop" {{ app_type == "desktop" ? "checked='checked'" : "" }}/>
                {{ "Application desktop" | trans }}
            </label>
        </div>
    </div>

    {% if app_type == "web" %}
        <div class="control-group callback-control-group">
            <label for="callback" class="control-label"><b>{{ "URL de callback" | trans }}</b></label>
            <div class="controls">
                <select name="scheme-callback" class="input-mini" style="min-height: 40px;">
                    <option value="http://">http://</option>
                    <option value="https://">https://</option>
                </select>
                {{ _self.input("callback", callback, violations, "urlcallback") }}
            </div>
        </div>
    {% endif %}

    <div class="control-group">
        <div class="col-md-6 controls" style="margin-right: 25px; float: left">
        <a class="btn btn-warning" href="{{ path("developers_applications") }}">
            {{ "boutton::retour" | trans }}
        </a>
        </div>
        <div class="col-md-6" style="width: 50%; float: left">
        <button class="btn btn-info no-margin" type="submit" style="margin: 0;width: auto;min-width: 200px">
            {{ "boutton::valider" | trans }}
        </button>
        </div>

    </div>
  </form>
{% endblock %}

Phraseanet/templates/web/developers/applications.html.twig
{% extends "account/base.html.twig" %}

{% block title %}
    {{ "Client applications" | trans }}
{% endblock %}

{% set selected = "developer" %}

{% block content_account %}
    <div class="row-fluid">
        <div class="span7">
            <div id="content-apps">
                <h1>Phraseanet Developer Center</h1>
                <h3>{{ "Mes applications" | trans }}</h3>
                {% if applications|length > 0 %}
                    <ul class="app-list unstyled">
                        {% for application in applications %}
                              <li id="app_{{ application.getId() }}">
                                    <a href="#appModal-{{ loop.index }}" role="button" data-toggle="modal" class="pull-right btn btn-danger btn-small" type="button">
                                        {{ "button::supprimer" | trans }}
                                    </a>
                                    <!-- Modal -->
                                    <div id="appModal-{{ loop.index }}" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                            <h3 id="myModalLabel">{{ application.getName() }}</h3>
                                        </div>
                                        <div class="modal-body">
                                            <p>{{ "Are you sure you want to delete this application?" | trans }} </p>
                                        </div>
                                        <div class="modal-footer">
                                            <button class="btn" data-dismiss="modal" aria-hidden="true">{{ "No" | trans }}</button>
                                            <a href="{{ path("delete_developers_application", {"application" : application.getId()}) }}" class="delete-app btn btn-info">{{ "Yes" | trans }}</a>
                                        </div>
                                    </div>
                                    <p class="app-row">
                                      <strong>
                                        <a  class="link" href="{{ path("developers_application", {"application" : application.getId}) }}">
                                            {{ application.getName() }}
                                        </a>
                                      </strong>
                                    </p>
                                    <p class="app-row">{{ application.getDescription()|truncate(120, true, "...") }}</p>
                              </li>
                        {%endfor%}
                    </ul>
                {% else %}
                    <div>
                      {{ "Aucune application creee." | trans }}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="span5">
            <div class="well well-small">
                <p>{{ "Decouvrez la documentation" | trans }}</p>
                <a href="https://docs.phraseanet.com/4.0/en/Devel/" target="_blank" class="btn btn-large text-center input-block-level">
                    {{ "Demarrer avec l\'API Phraseanet" | trans }}
                </a>
            </div>
            <div class="well well-small">
                <p>{{ "Creez une application pour commencer a utiliser l\'API Phraseanet" | trans }}</p>
                <a href="{{ path("developers_application_new") }}" class="btn-info btn btn-large text-center input-block-level">
                    {{ "Creer une nouvelle applications" | trans }}
                </a>
            </div>
        </div>
    </div>
    <script>
     $('a.delete-app').bind('click', function (e) {
            e.preventDefault();
            var $this = $(this);
            var li = $this.closest('li');

            $.ajax({
                type: 'DELETE',
                url: $this.attr('href'),
                dataType: 'json',
                data: {},
                success: function success(data) {
                    if (data.success) {
                        li.find('.modal').modal('hide');
                        li.remove();
                    }
                }
            });
        });
    </script>

{% endblock %}